VATSIM-UK/uk-controller-plugin

- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj
- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj.filters
- msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj
- msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj.filters
- src/airfield/AirfieldOwnershipManager.cpp
- src/controller/ControllerPositionCollection.cpp
- src/controller/TranslateFrequencyAbbreviation.cpp
- src/controller/TranslateFrequencyAbbreviation.h
- src/plugin/UKPlugin.cpp
- src/update/PluginVersion.cpp
- src/update/PluginVersion.h
- test/test/controller/ControllerPositionCollectionTest.cpp
- test/test/controller/TranslateFrequencyAbbreviationTest.cpp
Fix #38
Fix #23 
- Update initial controller load to explicitly load the users controller
- Recognise special positions such as ESSEX and also reasonable abbreviations (e.g. ESX)
> Fix initial controller load

- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj
- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj.filters
- msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj
- msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj.filters
- src/countdown/CountdownRenderer.cpp
- src/countdown/CountdownRenderer.h
- src/historytrail/HistoryTrailRenderer.cpp
- src/historytrail/HistoryTrailRenderer.h
- src/hold/HoldRenderer.cpp
- src/hold/HoldRenderer.h
- src/minstack/MinStackRenderer.cpp
- src/minstack/MinStackRenderer.h
- src/radarscreen/PositionResetCommand.cpp
- src/radarscreen/PositionResetCommand.h
- src/radarscreen/RadarRenderableCollection.cpp
- src/radarscreen/RadarRenderableCollection.h
- src/radarscreen/RadarRenderableInterface.h
- src/radarscreen/RadarScreenFactory.cpp
- src/radarscreen/RadarScreenFactory.h
- src/radarscreen/ScreenControls.cpp
- src/radarscreen/ScreenControls.h
- src/radarscreen/UKRadarScreen.cpp
- src/radarscreen/UKRadarScreen.h
- test/mock/MockRadarRendererableInterface.h
- test/test/countdown/CountdownRendererTest.cpp
- test/test/hold/HoldRendererTest.cpp
- test/test/minstack/MinStackRendererTest.cpp
- test/test/radarscreen/PositionResetCommandTest.cpp
- test/test/radarscreen/RadarRenderableCollectionTest.cpp
Close #21 
- Adds command `.ukcp resetvisuals` to reset the screen position of all RadarRenderables, primarily useful for when things are off screen.
> Reset Renderable Objects

- src/bootstrap/ExternalsBootstrap.cpp
- src/bootstrap/ExternalsBootstrap.h
- src/bootstrap/InitialisePlugin.cpp
- src/bootstrap/PostInit.cpp
- src/log/LoggerBootstrap.cpp
- src/log/LoggerBootstrap.h
- src/pch/stdafx.h
- src/plugin/UKPlugin.cpp
- src/windows/WinApi.cpp
- src/windows/WinApi.h
- src/windows/WinApiInterface.h
- test/mock/MockWinApi.h
- test/test/bootstrap/ExternalsBootstrapTest.cpp
- test/test/log/LoggerBootstrapTest.cpp
Close #66 
- Add code to ExternalsBootstrap that creates the `EuroScope/ukcp` folder without iterating from the absolute root.
- Update WinApi to work using `std::filesystem` rather than the basic API functions.
> Folder creation

- src/controller/ActiveCallsignCollection.cpp
- test/test/controller/ActiveCallsignCollectionTest.cpp
When a controller changes primary frequencies, we don't get a disconnect
event if it's the user. Therefore, just remove the current user callsign
from the currently active array.
> Fix #81: ES Crash When Changing Primaries

- src/hold/HoldManager.cpp
- src/plugin/UKPlugin.cpp
Flightplan disconnect events were being supressed.
> Fix #80: Aircraft Not Removed From Holds On Disconnect

- src/airfield/ControllerAirfieldOwnershipHandler.cpp
- src/controller/ControllerPosition.cpp
- src/controller/ControllerPosition.h
- src/metar/PressureMonitor.cpp
- src/metar/PressureMonitor.h
- src/metar/PressureMonitorBootstrap.cpp
- test/test/controller/ControllerPositionTest.cpp
- test/test/metar/PressureMonitorTest.cpp
- Only send a QNH update message if the user is concerned (ie, may have topdown responsibility) on the airfield in question.
> 89 qnh updates on concerned

- src/controller/ActiveCallsignMonitor.cpp
- src/controller/ControllerPositionCollection.cpp
- src/controller/ControllerPositionCollection.h
- src/controller/ControllerPositionParser.cpp
- src/controller/ControllerPositionParser.h
- test/test/controller/ActiveCallsignMonitorTest.cpp
- test/test/controller/ControllerPositionCollectionTest.cpp
- test/test/controller/ControllerPositionParserTest.cpp
- Remove restrictions on dependency controller position callsign formats, so we can facilitate positions such as Blackdog and Hotspur.
- Use the facility type when doing ActiveCallsign calculations, to allow us to differentiate when APP and TWR positions share a frequency.
> Controller Position Fixes

- src/dependency/UpdateDependencies.cpp
- test/test/dependency/UpdateDependenciesTest.cpp
- At the moment, if we don't have a dependency on the file-system but its contained in the list file (e.g. a download failed in the past), we don't try to redownload it.
- This change downloads any missing files regardless.
> Always Download Dependency If Not On Filesystem

- src/controller/ActiveCallsignMonitor.cpp
- test/test/controller/ActiveCallsignMonitorTest.cpp
- Changes ActiveCallsignMonitor to check that frequencies haven't changed in controller updates
> Fix #164: Incorrect Departure Frequency

- src/countdown/CountdownRenderer.h
- src/countdown/TimerConfigurationDialog.cpp
Allow timers of up to 3600 seconds.
> Fix #167: Longer Timers

- docs/TAG_FUNCTIONS.md
- src/euroscope/EuroScopeCFlightPlanInterface.h
- src/euroscope/EuroScopeCFlightPlanWrapper.cpp
- src/euroscope/EuroScopeCFlightPlanWrapper.h
- src/stands/StandEventHandler.cpp
- src/stands/StandEventHandler.h
- src/stands/StandModule.cpp
- test/mock/MockEuroScopeCFlightplanInterface.h
- test/test/stands/StandEventHandlerTest.cpp
- test/test/stands/StandModuleTest.cpp
- Annotate flight strips when stands are assigned so that they can be seen in vSMR
- Add an edit box so that stands may be typed in
- Prevent non-controllers from assigning stands
> Stand assignment textbox

- src/integration/ExternalMessageEventHandler.cpp
Technically, we should call with HWND_MESSAGE when finding the window to ensurethat we only find the
message-only window. Doesnt affect production at all.
> fix(externalintegrations): make debug command handler message only

- src/intention/SectorExitPointLelna.cpp
- test/test/intention/SectorExitPointLelnaTest.cpp
Add the H5 intention code for arrivals into airports in Brest FIR (LFRR) with the exception of LFRC
Fix #200
> feat(sectorexitlelna.cpp): add H5 intention code

- src/websocket/WebsocketConnection.cpp
This is a new code that's started coming up very rarely (it appears after someone stays connected for several hours), but needs to be treated as a reason to reset the websocket connection.
Fix #203
> fix(websocket): add local system aborted code to websocket resets

- src/squawk/SquawkGenerator.cpp
- test/test/squawk/SquawkGeneratorTest.cpp
If a user didn't have an ActiveCallsign, the ActiveCallsigns would throw an exception that would be
uncaught (e.g. if not PRIM'd up)
Fix #208
> fix(squawk): unhandled exception when forcing local squawk recycle

- src/websocket/WebsocketConnection.cpp
- src/websocket/WebsocketConnection.h
For some reason, the websocket stops receiving events after a while. To try and maintain
functionality whilst we fix this, reset the socket after 5 minutes of inactivity.
> fix(websocket): reset websocket after period of inactivity

- src/releases/DepartureReleaseEventHandler.cpp
Releases were being accessed by reference, which would go out of scope during the asynchronous task.
fix #289
> fix(departure-releases): fix crash when acknowledging departure releases

- docs/UserGuide/Features/DepartureReleases.md
- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj
- msvc/UKControllerPlugin/UKControllerPlugin.vcxproj.filters
- src/releases/DepartureReleaseRequestView.cpp
The colours were a bit mixed up and the User Guide doesnt describe what they mean
fix #291
> fix(departure-releases): fix colours in the release status view and add documentation

- src/push/PollingPushEventConnection.cpp
The "are we doing a thing" check needs to be set outside of the async function.
> fix(plugin-events): fix race condition when requesting event updates

- src/plugin/stands/StandEventHandler.cpp
- src/plugin/stands/StandEventHandler.h
There are potential crash points due to lack of concurrency checking.
fix #310
> fix(stands): fix concurrency issues with stand assignments

- src/plugin/push/PollingPushEventConnection.cpp
- test/plugin/push/PollingPushEventConnectionTest.cpp
If the data coming back was an array, it didn't check any further so could break on iterator deref.
fix #313
> fix(push-events): fix potential crash situation in push events

- src/plugin/bootstrap/DllInterface.cpp
- src/plugin/bootstrap/InitialisePlugin.cpp
- src/plugin/bootstrap/InitialisePlugin.h
- src/utils/CMakeLists.txt
- src/utils/update/CheckDevelopmentVersion.cpp
- src/utils/update/CheckDevelopmentVersion.h
- test/utils/CMakeLists.txt
- test/utils/update/CheckDevelopmentVersionTest.cpp
It was crashing when you shutdown the plugin if the core binary is loaded directly
fix #317
> fix(bootstrap): fix euroscope crash in development mode

- src/plugin/srd/SrdSearchDialog.cpp
The SRD only goes up to the FIR boundary / some EI airfields.
If the airfield is outside the FIR/EI, don't prepopulate the destination airfield.
fix #380
> fix(srd): only prepopulate SRD destination for EG and EI airfields

- .github/workflows/build.yml
- package.json
Some BC-breaking features coming up and moving forward, we may want to have the option to release experimental features early and to coordinate with ops for the controller pack. This adds the beta branch for semantic release purposes.
> chore(versions): Have a beta branch to put breaking features

- docs/UserGuide/Features/MissedApproaches.md
- resource/UKControllerPlugin.rc
- src/plugin/missedapproach/MissedApproachAudioAlert.cpp
- src/plugin/missedapproach/MissedApproachAudioAlert.h
- src/plugin/missedapproach/MissedApproachRenderer.cpp
- test/plugin/missedapproach/MissedApproachAudioAlertTest.cpp
Splits the missed approach criteria into two categories.
As before, you can choose to alert when you're providing a certain service at an airfield. For example, when providing Final Approach.
Before, the airfield list used to mean "but only at these airfields". It now means "but always alert me at these airfields regardless of service provision".
This allows, for example, Heathrow controllers to be alerted whenever a missed approach occurs at Northolt or Farnborough, as this information is relevant to them.
Fix #383
> feat(missedapproach): Allow airfields to always alert regardless of service provision

- src/plugin/metar/MetarsUpdatedPushEventProcessor.cpp
- test/plugin/metar/MetarsUpdatedPushEventProcessorTest.cpp
The API event was in the incorrect format. This change modifies the API event to have the correct
format.
fix #395
> fix(metars): metars not updating when they should

- src/plugin/push/PushEventProxyHandler.cpp
Due to some interesting string buffer issues with window enumeration, the push events never propagated
across to the other connection. This fixes the buffering so it properly detects proxy windows.
Fix #397
> fix(push-events): Push events not proxying to second EuroScope instance

- src/plugin/CMakeLists.txt
- src/plugin/push/ProxyPushDataSync.cpp
- src/plugin/push/ProxyPushDataSync.h
- src/plugin/push/PushEventBootstrap.cpp
- test/plugin/CMakeLists.txt
- test/plugin/push/ProxyPushDataSyncTest.cpp
- test/plugin/push/PushEventBootstrapTest.cpp
Until now, some push events (stands etc) were not syncing up when a second
instance of EuroScope was started. This fixes the synchronisation.
Fix #399
> fix(push-events): data not synchronising on second instance startup

- src/plugin/intention/SectorExitRepositoryFactory.cpp
- test/plugin/intention/SectorExitRepositoryTest.cpp
K2 is for TYNE exit - GOREV is between TINAC and PETIL so also K2
> fix(intentioncode): add GOREV as exit fix for K2 intention code

- src/plugin/CMakeLists.txt
- src/plugin/controller/ControllerPositionHierarchy.cpp
- src/plugin/controller/ControllerPositionHierarchy.h
- src/plugin/handoff/ClearCacheOnActiveCallsignChanges.cpp
- src/plugin/handoff/ClearCacheOnActiveCallsignChanges.h
- src/plugin/handoff/DepartureHandoffResolver.cpp
- src/plugin/handoff/DepartureHandoffResolver.h
- src/plugin/handoff/HandoffEventHandler.cpp
- src/plugin/handoff/HandoffEventHandler.h
- src/plugin/handoff/HandoffModule.cpp
- src/plugin/handoff/ResolvedHandoff.cpp
- src/plugin/handoff/ResolvedHandoff.h
- test/plugin/CMakeLists.txt
- test/plugin/controller/ControllerPositionHierarchyTest.cpp
- test/plugin/handoff/ClearCacheOnActiveCallsignChangesTest.cpp
- test/plugin/handoff/DepartureHandoffResolverTest.cpp
- test/plugin/handoff/HandoffCacheTest.cpp
- test/plugin/handoff/HandoffEventHandlerTest.cpp
It was hanging on to old handoffs when controllers log on if the handoff
was from the airfield hierarchy.
Fix #412
> fix(handoffs): Handoffs not repopulating when controllers log on

- src/plugin/metar/MetarModule.cpp
- src/plugin/metar/MetarsUpdatedPushEventProcessor.cpp
- src/plugin/metar/MetarsUpdatedPushEventProcessor.h
- test/plugin/CMakeLists.txt
- test/plugin/metar/MetarsUpdatedPushEventProcessorTest.cpp
- test/plugin/mock/MockMetarEventHandler.h
- test/plugin/pch/pch.h
Previously, the metar events weren't hooked up properly so the pressure
monitor wasn't firing. This fixes that.
Fix #409
> fix(pressuremonitor): Trigger pressure monitor updates correctly

- src/plugin/intention/SectorExitRepositoryFactory.cpp
- test/plugin/intention/SectorExitRepositoryTest.cpp
> fix(intention): add golum exit point for copenhagen

- src/plugin/wake/WakeCalculatorDisplay.cpp
It was sometimes hard to tell when there wasn't a wake interval because
it couldn't be worked out (or because of a bug) and when there legitimately isn't one.
This makes the default display to be a double dash. If two aircraft are selected such that
no interval applies (e.g. LM followed by LM), it will instead display N/A which makes it clear
to the user that there is no applicable interval.
Resolves #425
> feat(wake): Add not applicable to wake calculator display

- src/plugin/graphics/FontManager.cpp
Some users don't have the EuroScope font. Use Segoe UI as a fallback,
it doesn't look the best, but better than nothing!
Fixes #433
> fix(fonts): Provide fallback font if EuroScope is not installed

- src/plugin/euroscope/GeneralSettingsConfigurationBootstrap.cpp
- src/updater/dllmain.cpp
- src/utils/CMakeLists.txt
- src/utils/update/BootstrapReleaseChannelSettings.cpp
- src/utils/update/BootstrapReleaseChannelSettings.h
- test/utils/CMakeLists.txt
- test/utils/update/BootstrapReleaseChannelSettingsTest.cpp
It was defaulting to stable as the settings file was not loaded
> fix(updater): Updater not respecting selected release channel

- src/plugin/hold/HoldDisplay.cpp
We were returning the entire function rather than just skipping the display
of the timer.
> fix(hold): Hold display breaking when aircraft not in proximity

- src/plugin/historytrail/HistoryTrailRenderer.cpp
We weren't resetting the pen/brush after each run, so the first dot of the
second aircraft onwards was always invisible.
Fix #436
> fix(historytrails): Missing first dot on faded trails

- src/plugin/oceanic/OceanicEventHandler.cpp
- src/plugin/oceanic/OceanicEventHandler.h
The map was being cleared during update which in turn caused issues
if the map was being accessed for tag items.
Fixes #455
> fix(oceanic): Crash when updating clearances

- src/plugin/euroscope/EuroScopeCFlightPlanWrapper.cpp
Relates to https://github.com/VATSIM-UK/uk-controller-api/issues/923
> fix(squawk): treat msfs 1234 default squawk as unassigned

- src/utils/api/ApiRequestBuilder.cpp
- src/utils/api/ApiUrlBuilder.cpp
- test/testingutils/helper/ApiRequestHelperFunctions.cpp
- test/utils/api/ApiBootstrapTest.cpp
- test/utils/api/ApiCurlRequestFactoryTest.cpp
- test/utils/api/ApiFactoryTest.cpp
- test/utils/api/ApiHelperTest.cpp
- test/utils/api/ApiRequestBuilderTest.cpp
- test/utils/api/ApiUrlBuilderTest.cpp
- test/utils/api/CurlApiRequestPerformerTest.cpp
Compliments https://github.com/VATSIM-UK/uk-controller-api/pull/956 - prefix all the api routes so that we follow a more standard Laravel setup.
> feat(api): use api prefix for all routes

- src/plugin/CMakeLists.txt
- src/plugin/euroscope/RunwayDialogAwareInterface.h
- src/plugin/handoff/ClearCacheOnRunwayDialogSave.cpp
- src/plugin/handoff/ClearCacheOnRunwayDialogSave.h
- src/plugin/handoff/HandoffModule.cpp
- test/plugin/CMakeLists.txt
- test/plugin/handoff/ClearCacheOnRunwayDialogSaveTest.cpp
- test/plugin/handoff/HandoffModuleTest.cpp
Runway dialog changes do trigger a SID change, but do not trigger a FP change event.
This means the plugin does not update the departure frequencies of any FPs that had
an airfield resolved handoff, even if the new SID (after the runway dialog change) would
have had a different controller. This fixes that by clearing the handoff cache after
a runway dialog change.
fix #480
> fix(handoff): departure frequencies not updating after runway dialog change

- src/plugin/intention/IntentionCodeBootstrapProvider.cpp
- test/plugin/intention/IntentionCodeBootstrapProviderTest.cpp
Intention codes weren't clearing on FP/Controller events, leading to stale codes.
> fix: invalidate intention code caches on controller and fp events

- src/plugin/CMakeLists.txt
- src/plugin/geometry/Measurement.cpp
- src/plugin/geometry/Measurement.h
- src/plugin/geometry/MeasurementUnit.cpp
- src/plugin/geometry/MeasurementUnit.h
- src/plugin/geometry/MeasurementUnitFactory.cpp
- src/plugin/geometry/MeasurementUnitFactory.h
- src/plugin/geometry/MeasurementUnitType.h
- src/plugin/hold/HoldDisplay.cpp
- src/plugin/hold/HoldDisplay.h
- src/plugin/hold/HoldDisplayFunctions.cpp
- src/plugin/hold/HoldDisplayFunctions.h
- src/plugin/hold/HoldingData.cpp
- src/plugin/hold/HoldingData.h
- src/plugin/hold/HoldingDataSerializer.cpp
- test/plugin/CMakeLists.txt
- test/plugin/geometry/MeasurementUnitFactoryTest.cpp
- test/plugin/hold/HoldDisplayFunctionsTest.cpp
- test/plugin/hold/HoldDisplayTest.cpp
- test/plugin/hold/HoldModuleTest.cpp
- test/plugin/hold/HoldingDataSerializerTest.cpp
- test/plugin/hold/PublishedHoldCollectionFactoryTest.cpp
- Display the outbound leg details in the hold information display
- Show the description of the hold (for holds with multiple published holds)
- Allow switching between published holds on the information display
> Hold outbound leg details

- .github/workflows/build.yml
- src/plugin/oceanic/OceanicEventHandler.cpp
- src/plugin/oceanic/OceanicEventHandler.h
Fixes a crash if you try to open the oceanic clearance dialog when using the oceanic clearance tag items. This crash happens because the mutex covering the clearance map is locked at the start of TagFunction and wont unlock until the window has been closed. This causes the same ES thread to come along later (to display the tag items, try to lock the mutex, and everything explodes.
This change fixes the issue by scoping the mutex to a new function that has only the responsibility to grab the value from the map (or use the default if required). That way, subsequent calls can access the map properly.
Fixes #511
> fix: oceanic tag items crash

- src/plugin/bootstrap/ExternalsBootstrap.cpp
- src/plugin/bootstrap/ExternalsBootstrap.h
- src/utils/windows/WinApi.cpp
- test/plugin/bootstrap/ExternalsBootstrapTest.cpp
Changes how we open the API key selection window, as a recent ES update means it doesn't open properly.
Fix #514
> 514 api key selection

- src/utils/windows/WinApi.cpp
This change introduces backwards compatibility with EuroScope < 3.2.3 so that the API settings selection dialog shows properly in both versions.
> fix: api settings selection for ES3.2.21r34

- src/plugin/historytrail/AircraftHistoryTrail.cpp
- src/plugin/historytrail/AircraftHistoryTrail.h
- src/plugin/historytrail/HistoryTrailRenderer.cpp
- src/plugin/historytrail/HistoryTrailRenderer.h
- src/plugin/historytrail/HistoryTrailRepository.cpp
- src/plugin/historytrail/HistoryTrailRepository.h
- test/plugin/historytrail/AircraftHistoryTrailTest.cpp
- test/plugin/historytrail/HistoryTrailRepositoryTest.cpp
Improves performance of history trail rendering by approx. 25%
- Rather than do a bunch of if-statements on each dot to decide what kind of dot to draw on each pass, we can calculate (as a lambda) what the draw is ahead of time, whenever the ASR is loaded, or the configuration menu is saved.
- Rather than check if the dot is the first on each iteration, we start iterating from the second.
- Skip iteration altogether if there's only one dot.
- The "reduce per dot" for degrading trails can be calculated up-front.
- Change the storage mechanism of trails themselves to be a Vector rather than a Deque - this is better suited to the types of iteration we do in history trails.
> History trail performance

- src/plugin/historytrail/HistoryTrailRenderer.cpp
Caused by the change in direction of the trail dots, when the trails got sufficiently long, the "begin" dot, which was the last in the trail would go offscreen, causing the trail not to be shown.
> fix: history trail dots disappearing

- src/plugin/ecfmp/AircraftFlowMeasureMap.cpp
- test/plugin/ecfmp/AircraftFlowMeasureMapTest.cpp
The flowMeasureCallsignMap wasnt initialised unless an aircraft had a given flow measure apply to it. So when that flow measure expired, an out of range exception would be thrown when it tried to access the map.
Fixes #547
Fixes #538
> fix: ecfmp throws exception when flow measure has no aircraft

- src/plugin/stands/StandEventHandler.cpp
- src/plugin/stands/StandEventHandler.h
- src/plugin/stands/StandModule.cpp
- src/utils/api/ApiCurlRequestFactory.cpp
- src/utils/api/CurlApiRequestPerformer.cpp
- test/plugin/stands/StandEventHandlerTest.cpp
- test/plugin/stands/StandModuleTest.cpp
- test/testingutils/test/ApiExpectation.cpp
- test/testingutils/test/ApiExpectation.h
- test/testingutils/test/ApiResponseExpectation.h
- test/utils/api/ApiCurlRequestFactoryTest.cpp
Adds functionality to request that the API automatically assign a stand to a given aircraft. Works for both departure (based on the lat/lon) and arrivals.
> Stands auto request

- src/plugin/wake/WakeCalculatorDisplay.cpp
- src/plugin/wake/WakeCalculatorDisplay.h
- test/plugin/wake/WakeCalculatorDisplayTest.cpp
Makes the wake calculator collapsible so that it can be on screen without taking up a lot of space.
> feat: make wake calculator collapsible

- src/plugin/integration/OutboundIntegrationMessageHandler.cpp
- src/plugin/integration/OutboundIntegrationMessageHandler.h
- src/plugin/intention/IntentionCodeUpdatedMessage.cpp
- src/utils/CMakeLists.txt
- src/utils/api/ApiBootstrap.cpp
- src/utils/log/ApiLogger.cpp
- src/utils/log/ApiLogger.h
- src/utils/log/ApiLoggerInterface.h
- src/utils/log/LoggerFunctions.cpp
- src/utils/log/LoggerFunctions.h
- test/testingutils/test/ApiTestCase.h
- test/utils/CMakeLists.txt
- test/utils/log/ApiLoggerTest.cpp
Send exception info to the API so that we can collect these more readily without requiring reports.
Probably resolves #549 via catching issues related to malformed JSON.
> feat: log fatal exceptions to the api
