VATSIM-UK/uk-controller-plugin

src/intention/SectorExitRepositoryFactory.cpp
test/test/intention/SectorExitRepositoryTest.cpp

Fix Copenhagen Intention Codes

---

src/websocket/WebsocketConnection.cpp
src/websocket/WebsocketConnection.h

- Fix the websocket thread crashing due to the sleeps introduced.

Fix Websocket Termination

---

src/curl/CurlApi.cpp

Write cURL Error Code To Logs

---

src/plugin/UKPlugin.cpp

Fix #104: Squawks Not Assigning

---

src/bootstrap/InitialisePlugin.cpp

Fix #107: Ownership Commands

---

src/bootstrap/DllInterface.cpp

- Catch all bootstrap related exceptions so we know what they are.

Catch All Exceptions On Bootstrap

---

src/dependency/UpdateDependencies.cpp
src/dependency/UpdateDependencies.h
test/test/dependency/UpdateDependenciesTest.cpp

Close #114 
Only download API data if required.

114 download dependencies if needed

---

msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj
msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj.filters
src/intention/SectorExitPointScottish.h
src/intention/SectorExitRepositoryFactory.cpp
test/test/intention/SectorExitRepositoryTest.cpp

RINTI was missing 
INBOB was an error with the direction

Missing RINTI and INBOB intention codes

---

src/bootstrap/DllInterface.cpp
src/bootstrap/ExternalsBootstrap.cpp
src/log/LoggerBootstrap.cpp
src/windows/WinApi.cpp
src/windows/WinApi.h
src/windows/WinApiInterface.h
test/mock/MockWinApi.h
test/test/bootstrap/ExternalsBootstrapTest.cpp

Get a bit more exception info so we can handle bootstrap crashes better.

More exception info

---

src/intention/BrusselsAirfieldGroup.cpp
src/intention/BrusselsAirfieldGroup.h
test/test/intention/BrusselsAirfieldGroupTest.cpp

feat(intention): add secondary EX code for Brussels airports

---

msvc/UKControllerPlugin/UKControllerPlugin.vcxproj
msvc/UKControllerPlugin/UKControllerPlugin.vcxproj.filters
msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj
msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj.filters
src/api/ApiHelper.cpp
src/api/ApiHelper.h
src/api/ApiInterface.h
src/api/ApiRequestBuilder.cpp
src/api/ApiRequestBuilder.h
src/bootstrap/PersistenceContainer.h
src/websocket/PollingWebsocketConnection.cpp
src/websocket/PollingWebsocketConnection.h
src/websocket/WebsocketBootstrap.cpp
test/mock/MockApiInterface.h
test/test/api/ApiHelperTest.cpp
test/test/api/ApiRequestBuilderTest.cpp
test/test/websocket/PollingWebsocketConnectionTest.cpp

250 websocket poller

---

docs/TAG_ITEMS.md
docs/UserGuide/Features/Nattrak.md
src/oceanic/OceanicEventHandler.cpp
src/oceanic/OceanicEventHandler.h
src/oceanic/OceanicModule.cpp
test/test/oceanic/OceanicEventHandlerTest.cpp
test/test/oceanic/OceanicModuleTest.cpp

feat(oceanic): add cleared track and entry estimate TAG items

---

src/api/ApiHelper.cpp
src/api/ApiHelper.h
src/api/ApiInterface.h
src/api/ApiRequestBuilder.cpp
src/api/ApiRequestBuilder.h
src/curl/CurlRequest.cpp
src/curl/CurlRequest.h
test/helper/Matchers.h
test/mock/MockApiInterface.h
test/test/api/ApiHelperTest.cpp
test/test/api/ApiRequestBuilderTest.cpp

API changes for departure releases

feat(releases): Add API calls for departure releases

---

msvc/UKControllerPlugin/UKControllerPlugin.vcxproj
msvc/UKControllerPlugin/UKControllerPlugin.vcxproj.filters
msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj
msvc/UKControllerPluginTest/UKControllerPluginTest.vcxproj.filters
src/euroscope/EuroScopeCFlightPlanInterface.h
src/euroscope/EuroScopeCFlightPlanWrapper.cpp
src/euroscope/EuroScopeCFlightPlanWrapper.h
src/euroscope/EuroscopeFlightplanListInterface.h
src/euroscope/EuroscopeFlightplanListWrapper.cpp
src/euroscope/EuroscopeFlightplanListWrapper.h
src/euroscope/EuroscopePluginLoopbackInterface.h
src/plugin/UKPlugin.cpp
src/plugin/UKPlugin.h
test/mock/MockEuroScopeCFlightplanInterface.h
test/mock/MockEuroscopeFlightplanList.h
test/mock/MockEuroscopePluginLoopbackInterface.h

Add additional bits to EuroScopes class wrappers for departure releases.

feat(euroscope): Add additional EuroScope interfaces

---

src/euroscope/EuroscopePluginLoopbackInterface.h
src/plugin/UKPlugin.cpp
src/plugin/UKPlugin.h
src/releases/DepartureReleaseEventHandler.cpp
test/mock/MockEuroscopePluginLoopbackInterface.h
test/test/releases/DepartureReleaseEventHandlerTest.cpp

fix(departure-releases): Fix releases not being approved through decision list

---

src/releases/ApproveDepartureReleaseDialog.cpp

If someone took 30 seconds to fill in the form for an immediate release, it would shave thirty
seconds off any expiry time. This change makes the plugin changed the released at time to "now" if
its in the past.
fix #297

fix(departure-releases): treat releases at current minute as released at exactly now

---

src/utils/helper/HelperFunctions.cpp

We were converting the timestamp back using local time
fix #190

fix(edt): fix timezone issue with estimated departure times

---

script/IntegrationClientSocketTest.cpp
src/plugin/integration/ClientInitialisationManager.cpp
src/plugin/integration/ClientInitialisationManager.h
src/plugin/integration/SocketConnection.cpp
src/plugin/integration/SocketWrapper.cpp
src/plugin/integration/SocketWrapper.h

fix(integration): Fix messages not being received from clients

---

src/plugin/CMakeLists.txt
src/plugin/srd/SrdSearchDialog.cpp
src/plugin/srd/SrdSearchDialog.h
src/plugin/srd/SrdSearchHandler.cpp
src/plugin/srd/SrdSearchHandler.h
src/utils/dialog/DialogCallArgument.h
src/utils/srd/SrdSearchParameters.h
test/plugin/CMakeLists.txt
test/plugin/srd/SrdSearchHandlerTest.cpp

feat(srd): Prepopulate SRD search from flightplan

---

src/plugin/intention/IntentionCodeGenerator.cpp
test/plugin/intention/IntentionCodeGeneratorTest.cpp

fix(intentioncode): euroscope freezing when aircraft cleared beyond exit

---

src/plugin/initialheading/InitialHeadingEventHandler.cpp
src/plugin/initialheading/InitialHeadingEventHandler.h
test/plugin/initialheading/InitialHeadingEventHandlerTest.cpp

fix(initialheading): Dont allow initial heading recycle on aircraft out of range

---

src/plugin/intention/IntentionCodeCache.cpp
src/plugin/intention/IntentionCodeCache.h
src/plugin/intention/IntentionCodeEventHandler.cpp
src/plugin/intention/IntentionCodeGenerator.cpp
src/plugin/intention/IntentionCodeGenerator.h
test/plugin/intention/IntentionCodeCacheTest.cpp
test/plugin/intention/IntentionCodeGeneratorTest.cpp

feat(intentioncode): Dont cancel intention codes after leaving the FIR

---

src/plugin/intention/SectorExitPointEtrat.cpp
src/plugin/intention/SectorExitPointEtrat.h
test/plugin/intention/SectorExitPointEtratTest.cpp

Adds the code for certain arrivals.
Resolves #458

feat(intentioncode): E3 intention code

---

src/plugin/oceanic/OceanicEventHandler.h
test/plugin/oceanic/OceanicEventHandlerTest.cpp

Format remains the same, new URL.
Resolves #452

fix(oceanic): Use new Nattrak API endpoint

---

src/plugin/flightinformationservice/FlightInformationServiceTagItem.cpp
test/plugin/flightinformationservice/FlightInformationServiceTagItemTest.cpp

fix(ukfis): Update UKFIS abbreviations

---

src/plugin/intention/SectorExitPointEtrat.cpp
test/plugin/intention/SectorExitPointEtratTest.cpp

E2 Max Level Change

---

src/plugin/intention/SectorExitRepositoryFactory.cpp
test/plugin/intention/SectorExitRepositoryTest.cpp

fix(intention): k3 intention code via larga

---

src/plugin/intention/SectorExitPointKonan.cpp
src/plugin/intention/SectorExitPointKonan.h
test/plugin/intention/SectorExitPointKonanTest.cpp

fix: konan d1 intention code

---

src/loader/dllmain.cpp
src/loader/loader/loader.cpp

Prompt the user to install the Visual C++ Redistributables when certain error codes appear on load.

Redistributables prompt

---

src/plugin/intention/SectorExitRepositoryFactory.cpp
test/plugin/intention/SectorExitRepositoryTest.cpp

fix: f intention code updates

---

src/plugin/intention/SectorExitRepositoryFactory.cpp
test/plugin/intention/SectorExitRepositoryTest.cpp

fix: irish G intention code directions

---

.github/workflows/build.yml
src/plugin/releases/EnrouteReleaseTypesSerializer.cpp

build: run actions on windows server 2022

---

src/plugin/euroscope/CallbackFunction.cpp
src/plugin/euroscope/CallbackFunction.h
src/plugin/euroscope/RadarScreenCallbackFunction.cpp
src/plugin/euroscope/RadarScreenCallbackFunction.h
src/plugin/notifications/UnreadNotificationsMessage.cpp
src/plugin/tag/RadarScreenTagFunction.cpp
src/plugin/tag/RadarScreenTagFunction.h
src/plugin/tag/TagFunction.cpp
src/plugin/tag/TagFunction.h
test/plugin/notifications/NotificationsEventHandlerTest.cpp
test/plugin/notifications/UnreadNotificationsMessageTest.cpp

Updates the notifications unread message to indicate where they can be actioned.

Notifications message update

---

src/plugin/command/CommandHandlerCollection.cpp
src/plugin/controller/ActiveCallsignCollection.cpp
src/plugin/controller/ControllerStatusEventHandlerCollection.cpp
src/plugin/controller/HandoffEventHandlerCollection.cpp
src/plugin/euroscope/RadarTargetEventHandlerCollection.cpp
src/plugin/flightplan/FlightPlanEventHandlerCollection.cpp
src/plugin/integration/IntegrationServer.cpp
src/plugin/intention/IntentionCodeEventHandlerCollection.cpp
src/plugin/metar/MetarEventHandlerCollection.cpp
src/plugin/plugin/FunctionCallEventHandler.cpp
src/plugin/plugin/UKPlugin.cpp
src/plugin/prenote/PrenoteMessageEventHandlerCollection.cpp
src/plugin/push/PushEventProcessorCollection.cpp
src/plugin/radarscreen/RadarRenderableCollection.cpp
src/plugin/timedevent/TimedEventCollection.cpp
src/utils/eventhandler/EuroscopeThreadEventProcessor.cpp
src/utils/eventhandler/EventStream.tpp
src/utils/log/LoggerFunctions.cpp
src/utils/log/LoggerFunctions.h

Adds logging to various event paths to log any fatal exceptions that occur.
Also removes a spurious logs from integration server.

Fatal exception logging

---

src/utils/api/ApiKeyRedirectUrlBuilder.cpp
test/utils/api/ApiKeyRedirectUrlBuilderTest.cpp

I forgot to change this after a recent API change.

fix: change user create api key path
